name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - name: Check code formatting
        run: npm run lint
        continue-on-error: true
        id: lint-check

      - name: Formatting Check Result
        if: steps.lint-check.outcome == 'failure'
        run: |
          echo "::warning::Code formatting issues detected. Run 'npm run format' locally to fix."
          exit 1
      - run: npm test
      - name: Build
        run: npm run build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}/'
          # Use placeholder values for CI builds to ensure the app builds without secrets
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL || 'https://placeholder.supabase.co' }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY || 'placeholder-key' }}
